receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "contest-hq"
          scrape_interval: 5s
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 10s
          relabel_configs:
            - source_labels: [__meta_docker_container_label_role]
              regex: web
              action: keep
            - source_labels: [__address__]
              regex: (.*):9394
              action: keep
            - source_labels: [__meta_docker_container_id]
              target_label: container_id

exporters:
  prometheus:
    endpoint: 0.0.0.0:9394

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
